### ISSUE TITLE
Each product within catalogue needs an assignment to a concept (domain ontology or eclass)

### ISSUE THREAD

**Issue by marcofranke** [nimble-platform/common#7]
The current indexed data set (catalogue2) contains products which have no assignment to a concrete class. Current proposal is to add the field  item_commodity_classification_uri in catalogue2. 

For release 3: Each product within the catalogue2 needs a value for the field item_commodity_classification_uri

**Comment by suatgonul** [comment]
Added the "item_commodity_classification_uri" field to the Solr index used for keeping the catalog information
