### ISSUE TITLE
Define default concept for product upload in which the user didn't choose a category

### ISSUE THREAD

**Issue by marcofranke** [nimble-platform/common#8]
The strict assignment of a product to a specific concept (domain ontology or eclass) needs also a default concept product. Each time the user doesn't choose categories, the default product have to be set.

As an outcome, the field item_commodity_classification_uri of a specific product would have the value (domain concept or eclass) or product. 

For that purpose, the concept product have to be defined including the default properties. This must be aligned to the generic properties the product fro the UI perspective

**Comment by suatgonul** [comment]
It's been decided that we won't allow product publishing without a category. So, the following issue will fix this one.

https://github.com/nimble-platform/frontend-service/issues/46

**Comment by suatgonul** [comment]
As indicated in the previous comment, although we expect each product to have at least on category, we still annotate products with a default category, which is kept in item_commodity_classification field. This is just a label. Do you also want an associated URI with this default category e.g. http://nimble-project/catalogue/Product. If so, do you want it as a dereferencable URI? If so, how will you use this URI, to query what?
